### ISSUE TITLE
"You've got to be joking. I need more data!" error on simple series

### ISSUE THREAD

**Issue by harmbuisman** [robjhyndman/forecast#211]
Reproduction:
Input:
library(forecast); ets(c(0,0,100))

Output:
Error in ets(c(0, 0, 100)) : You've got to be joking. I need more data!

I would expect no issues with a series like this, e.g. this does work: library(forecast); ets(c(100,100,100))

Version info:
This is forecast 6.2 
"R version 3.2.3 (2015-12-10)"

**Comment by mitchelloharawild** [comment]
When you run 
```R
ets(c(100,100,100))
```
You are actually running simple exponential smoothing (as all your data is constant)
```R
Simple exponential smoothing 

Call:
 ses(x = y, initial = "simple", alpha = 0.99999) 

  Smoothing parameters:
    alpha = 1 

  Initial states:
    l = 100 

  sigma:  0
```

In order to estimate the parameters in an ETS model, for example: `ets(c(0,0,100))`, you need at least 4 data points, and depending on the ETS method, up to about 30 data points (seasonality estimation)

**Comment by robjhyndman** [comment]
Note that etc(c(100,100,100)) is captured as a special case of constant data. But if a vector of 3 elements is not constant, then a model has to be estimated and that requires more than 3 observations.
