### ISSUE TITLE
Using sample as a variable name leads to error in forecast function

### ISSUE THREAD

**Issue by jain1510** [robjhyndman/forecast#256]
I was running an out of sample forecast on my fitted model. suppose there is a  data frame called 'parent' having 100 rows and 3 columns. I subset 'parent' in to two data frames. First is called 'sample' which has the first fifty rows and second is 'forecast' which has rows from 51 to 100. I fit my model using the 'sample' and then use the forecast function which throws an error. 

   m <- lm(z ~ x + y,data=sample)
   summary(m)
   f <- forecast.lm(m,forecast)

Error I see is : 

**Error in if (nrow(origdata) != length(fcast$x)) tspx <- NULL : 
 argument is of length zero**

1) Regression runs fine.
2) I am able to use the predict.lm function and it works perfect.
3) I try to use forecast and gives me an error.
4) I change the 'sample' to any other name(not reserved), forecast works and no error.
5) I thought it of as a buf because the base function predict.lm does not throw an error and not should forecast.lm 

Thanks.

**Comment by dashaub** [comment]
Consider naming your datasets something that doesn't already have a definition as a function (see what happens when you run `?sample` or `?forecast`?)

`lm()` is from the `stats` package, and `forecast.lm()` is for running on models created with `tslm()`. Is `x` or `y` a time variable? If you're just wanting to build a regular `lm` model, try this:
`
m <- lm(z ~ x + y, data = d1); f <- predict(m, newdata = d2)
` 


If you're just wanting to build a `tslm` model with a trend and seasonal component, try this:
`
m <- tslm(y ~. + trend + season, data = d1); f <- forecast.lm(m, newdata = d2)
`

**Comment by robjhyndman** [comment]
Yesterday I added some lines that would catch this error and return a more meaningful message to the user.
