### ISSUE TITLE
Easier support for multiple time series in auto.arima

### ISSUE THREAD

**Issue by SnurreJensen** [robjhyndman/forecast#289]
My understanding of auto.arima is that if you have multiple time series to forecast you need to have them as columns in the data. This could result in a very "wide" table. Would it be possible to support some sort of grouping setup with one or more columns indicating the groups and then just one column with the time series to forecast?

Among other things this would overcome situations:
- Where you do not know the number and names of time series to forecast. You just point to the "actuals" column and then the columns indicating your groups
- Where you have different values in XREG for your dependent. I'm sure you can create some looping scheme today to accomodate this, but it could be quite complex to set up.
- Where you dramatically increase the number of output columns because you need to have 3 additional output columns for point forecast, lower bound and upper bound for each input series.

**Comment by dashaub** [comment]
This would be much more clear if you would include a reproducible example showing the structure of your data. I'm not sure what you're talking about with "groups". Are you talking about this?
https://github.com/robjhyndman/hts

**Comment by SnurreJensen** [comment]
I've attaced an Excel sheet which I hope clarifies what I mean. The tab "columns" is where my time series are stored as columns - the "wide" format. The tab "groups" shows the "long" format.

I want to automatically create forecasts for each product using an explanatory binary variable if this is significant. Can the hts package accomplish this?

[Forecasting data structures.xlsx](https://github.com/robjhyndman/forecast/files/224492/Forecasting.data.structures.xlsx)

**Comment by dashaub** [comment]
This is a basic R data manipulation problem and not really specific to the "forecast" package. Try creating a dataframe with columns Product A through Promoc C and running something like this:
```
for(i in 1:3){
    results <- list()
    list[i] <- auto.arima(x = ts(myData[, i], f = 12), xreg = matrix(myData[, i + 3], ncol = 1)
}
```
To generate forecasts you can then run `lapply` on `results`. Better yet would be to split this into a product data frame and a promo data frame. Then the loop would select the `i` column for both the `x`and the `xreg` instead of `i + 3` for the `xreg`.

FYI if you only have one year of monthly data, `auto.arima` won't do much for you: you'll need more observations to support a complex specification. If you have a trend and no seasonal component a simple `lm` with a trend could be a decent choice.

**Comment by xavierjl70** [comment]
I am running an auto.arima . however, I have to group by and loop.
by_StateCode <- group_by(p4pcrtcalsumm, StateCode, MeasureId)
fit1 =  do(by_StateCode,tidy(auto.arima(RATE, seasonal= T, xreg=xi), data = p4pcrtcalsumm.
However, i am not able to predict or forecast. I am getting an error
frcst1 <- forecast(fits, h=10) or 

mydata.pred1 <- do(by_StateCode,tidy(predict(fit1, n.ahead=10,  data = p4pcrtcalsumm)))

error:
Error in ets(object, lambda = lambda, biasadj = biasadj, allow.multiplicative.trend = allow.multiplicative.trend,  : 
  y should be a univariate time series

**Comment by robjhyndman** [comment]
This is not a help site. Please ask on stackoverflow.com

**Comment by xavierjl70** [comment]
Thanks!
