### ISSUE TITLE
Use bsts as under the hood calculation for ets()?

### ISSUE THREAD

**Issue by paulhendricks** [robjhyndman/forecast#292]
Steve Scott has written a great package that performs state space modeling using Bayesian structural time series. I think this could be adopted to do linear state space innovations modeling in the forecast package. See here for the package: https://github.com/cran/bsts

Advantages:
* code is abstracted to a object oriented interface
* can place priors on the various states
* can use dynamic regressors, holidays, and arma components
* c++ for quick under the hood calculation

Disadvantages:
* re-write code
* perhaps different interface
* multiplicative errors may not be possible

Your thoughts @robjhyndman ?

**Comment by paulhendricks** [comment]
I would also check out: https://github.com/cran/Boom

**Comment by robjhyndman** [comment]
bsts uses a state space model with independent errors in the various equations. An innovations model has the same error in each equation.

In any case, it would be impossible to make a general state space package run as fast as ets() because we use various tricks specific to the modelling framework to make it run fast.
