### ISSUE TITLE
Refitting stlm objects

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#303]

**Comment by mitchelloharawild** [comment]
If `ets` is passed model (for re-fit), should the smoothing parameters should remain the same as the model which has been passed in?

```R
a <- ets(USAccDeaths)
b <- ets(USAccDeaths, model=a)
identical(a$par, b$par)
[1] FALSE
```

**Comment by robjhyndman** [comment]
If `use.initial.values=TRUE`, they will be identical:
```
a <- ets(USAccDeaths)
b <- ets(USAccDeaths, model=a, use.initial.values=TRUE)
identical(a$par,b$par)
[1] TRUE
```

**Comment by mitchelloharawild** [comment]
Added in #413

**Comment by robjhyndman** [comment]
There is a problem if the modelfunction is used:

```R
tsmod <- stlm(USAccDeaths, modelfunction=ar)
stlm(USAccDeaths, model=tsmod)
Error in stlm(USAccDeaths, model = tsmod) : Unknown model type
```

**Comment by robjhyndman** [comment]
If there's no easy fix, don't worry about it.

**Comment by mitchelloharawild** [comment]
Maybe not an easy fix for `ar`, because it doesn't have support for model re-fitting, however it can be tweaked to work for any function that supports re-fitting via the model argument.

That would involve saving the modelfunction used to the stlm object (for potential later use), and then setting:
```R
modelfunction <- function(x,...){return(model$modelfunction(x,model=model$model, ...))}
```

That way, users can use functions that support re-fitting, and they can also write wrappers that extend `ar` to support re-fitting.

**Comment by robjhyndman** [comment]
Got it. Please make that change, and we'll forget about ar for now. I might write my own AR function as a wrapper for ar (as I did with Arima) at some future time.
