### ISSUE TITLE
Environment variables issue with forecast.fracdiff

### ISSUE THREAD

**Issue by contstantine** [robjhyndman/forecast#366]
There is an issue where `forecast` looks for a variable in some environment where it does not exist... I have originally posted the issue on [StackOverflow](http://stackoverflow.com/questions/39500711/object-not-found-issue?noredirect=1#comment66321006_39500711). What it comes down to is that the function ...

```
brokenFunction <- function(train, test) {
	training = train
	print(exists('training'))
	predictions = test
	for (i in 1:length(test)){
		print(exists('training'))
		fit = fracdiff(x=training, nar=3, nma=1, h=0.00001)
		print(exists('training'))
		predictions[i] = forecast(fit, 1)$mean
		print(exists('training'))
		training = c(training, test[i])
	}
	return(predictions)
}
```

evaluates to the following...

```
> anotherBrokenFunction(train, test)
[1] TRUE
[1] TRUE
[1] TRUE
Error in eval(expr, envir, enclos) : object 'training' not found
```

However, this only happens when `fit` is the result of `fracdiff()`

**Comment by robjhyndman** [comment]
The problem is that `fracdiff` does not store enough information for `forecast` to use, and as it is not my function I can't fix it. `forecast` does it's best to find the data used when fitting the model, but if you next the call inside another function it has difficulty figuring out what happened. The solution is to add the data to the returned object, as per the stackexchange answer. Alternatively, use the `arfima` function instead of `fracdiff`.

**Comment by robjhyndman** [comment]
I found a fix, implemented in https://github.com/robjhyndman/forecast/commit/76526da54dfa5732290da080e001e3994758cba2

**Comment by contstantine** [comment]
Fantastic!
