### ISSUE TITLE
ggAcf won't pipe

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#381]
MRE
```
library(magrittr)
library(ggplot2)
library(fpp)
eggs %>% ggAcf
```

**Comment by mitchelloharawild** [comment]
The issue is because autoplot.acf tries to locate the timeseries from the
user's workspace, to get the tsp for the seasonal tick labels.
An ideal solution is one that doesn't involve searching outside the
function's scope... Is there any reason against having Acf() include a $x
(or a $tsp) to store the whole time series (or just the tsp of it)?
Then if the user is coming from acf(), we can just leave the tick labels as
default (or some generic gap of 4, or depending on the number of lags, etc.)

**Comment by robjhyndman** [comment]
OK. Then we can just store tsp in the acf object. Better than storing the whole time series as it takes less space.

**Comment by robjhyndman** [comment]
Now fixed in https://github.com/robjhyndman/forecast/commit/9b34f7e7029744c4ff48855e5179f42a7187ce04
