### ISSUE TITLE
Remove missing value warning from autoplot.ts()

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#391]
MRE:

```
library(ggplot2)
library(fpp)
autoplot(cbind(USAccDeaths/1e2,hsales))
```

**Comment by mitchelloharawild** [comment]
This is the ggplot style for overlapping different series:

```R
ggplot() + 
  geom_line(aes(x=time(USAccDeaths/1e2), y=USAccDeaths/1e2, colour="USAccDeaths")) + 
  geom_line(aes(x=time(hsales), y=hsales, colour="hsales"))
```
![rplot](https://cloud.githubusercontent.com/assets/16127127/20610833/a4f53dda-b2f3-11e6-97aa-b7fa70eb5386.png)

Note that the warning/message relating to scale is because the dataset is of type ts, and ggplot doesn't know how to handle it (I'm working on this).

---

Still unsure how I feel about geom_ts(), it's definitely not in the style of ggplot, but the convenience is undeniable :smile:. Try this out and let me know what you think.
```R
ggts <- function(object, colour=TRUE){
  tsdata <- data.frame(timeVal = as.numeric(time(object)), 
                       series = deparse(substitute(object)),
                       seriesVal = as.numeric(object))
  if(colour){
    geom_line(aes_(x=~timeVal, y=~seriesVal, group=~series, colour=~series), data=tsdata)
  }
  else{
    geom_line(aes_(x=~timeVal, y=~seriesVal, group=~series), data=tsdata)
  }
}

ggplot() + ggts(USAccDeaths/1e2) + ggts(hsales)
```

It definitely does some weird things (that will be hard to control for), like:
```R
autoplot(USAccDeaths/1e2) + ggts(hsales)
```

**Comment by robjhyndman** [comment]
Hadley will be here in a couple of weeks. We could ask him what he thinks of this. But I'm all in favour of convenience over purity.
