### ISSUE TITLE
Broaden baggedETS: user-defined forecast functions

### ISSUE THREAD

**Issue by AnscombesGimlet** [robjhyndman/forecast#600]
I would love to see user-defined forecast functions be allowed in the same manner as baggedETS works. Perhaps create a new, broader function which defaults to ETS? I know auto.arima will work, I've taken the source code and simply swapped the ets line with auto.arima just to test.

**Comment by saurav2608** [comment]
baggedETS is based on a paper co-authored by @robjhyndman. That paper is specific about bagging ETS methods. I am not sure about the theoretical aspect of using Arima. 
This function can be extended by allowing a FUN parameter to be passed to baggedETS function. (the function might have to be renamed as baggedFcast  or equivalent)

**Comment by mitchelloharawild** [comment]
From #616, using auto.arima with bagging is now possible using the `baggedModel` function.

**Comment by hbh3re** [comment]
Will `baggedModel` be extended to work with other forecast models? I currently get an error when trying to run it with something other than `ets` or `auto.arima`

**Comment by cbergmeir** [comment]
It should work with other models as well. Can you give a reproducible example of the error you are getting?

**Comment by hbh3re** [comment]
`baggedModel(woolyrnq, fn='auto.arima')` returns a fit model. 
But `baggedModel(woolyrnq, fn='tbats')` throws this error: 

`Error in match.arg(fn) : 'arg' should be one of “ets”, “auto.arima”`

I am running R version 3.5.1 and forecast version 8.4

**Comment by hbh3re** [comment]
Any thoughts? I believe the problem is with only passing one argument, `fn`, to `match.arg` in the first line of the `baggedModel` function (baggedModel.R - Line 53). From the `match.arg` documentation:

"In the one-argument form match.arg(arg), the choices are obtained from a default setting for the formal argument arg of the function from which match.arg was called. "

So here, the "choices" value that `fn` is being matched against is the default argument for `fn` in the `baggedModel` function definition, `fn=c("ets", "auto.arima")`. Thus `match.arg` throws an error whenever the given `fn` is not one of those default choices.

**Comment by cbergmeir** [comment]
Hi, yes, it will be easy to fix; I think I misunderstood how R uses these default parameters. I'll commit a fix in the next days.

**Comment by cbergmeir** [comment]
@robjhyndman in baggedModel line 53 we need to get rid of the match.arg to fix the problem. However, another point I think needs to be discussed:

Now we would have:
```
  # Add package info in case forecast not loaded
  fn <- utils::getFromNamespace(fn, "forecast")
```
This was introduced in a commit named "Fix to baggedModel when forecast package not loaded". However, what I don't like about this version is that now you need to pass the function by name and cannot pass directly a function as parameter, i.e., fn="ets" is ok, and fn=ets won't work. Also, the documentation of getFromNamespace states that the function should be used only during package development and not in production code. So I would prefer the classic:
```
fn <- match.fun(fn)
```
As, e.g., lapply does it. Thoughts?

**Comment by robjhyndman** [comment]
We could use NSE to avoid the quoting. Perhaps @mitchelloharawild can help here.

**Comment by mitchelloharawild** [comment]
This is my suggestion, which should maintain all functionality if someone has used partial string matching of 'ets' or 'auto.arima'...
```r
  if(!is.function(fn)){
    # Add package info in case forecast not loaded
    fn <- utils::getFromNamespace(match.arg(fn), "forecast")
  }
```

However, I think the better approach would be not matching anything and only accepting functions as inputs.

**Comment by cbergmeir** [comment]
@mitchelloharawild I think you still should get rid of the match.arg in the call, or try to run getFromNamespace without match.arg and if it fails then run with match.arg otherwise something like `baggedModel(woolyrnq,` fn='tbats')` will still give the error from above, and it will be fairly misleading now, as `baggedModel(woolyrnq,` fn=tbats)` will work.
