### ISSUE TITLE
Add arimax()

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#7]
I would like transfer function methodology to be added. We need to decide whether to use the Peter Young approach, as in the CAPTAIN toolbox in Matlab, or a state space approach as in Brockwell & Davis, or something else.

**Comment by BrianMiner** [comment]
I would LOVE to see this. Given some of the weaknesses with the TSA package, there is essentially nothing in R that allows building intervention / interrupted time series models. Given how robust 'forecast' has become, it would be the perfect place!

**Comment by ekote** [comment]
Hi @robjhyndman
I would like to implement ARIMAX in open source [Spark-timeseries](https://github.com/sryza/spark-timeseries) (scala) library because it hasn't existed yet.
You [wrote](http://robjhyndman.com/hyndsight/arimax/):
> The arimax() function from the TSA package fits the transfer function model (but not the ARIMAX model).

Could you explain how the transfer function model work and how should ARIMAX be pragmatically implemented? Or any research on which I can base on my code.
Thank you!
Estera

**Comment by robjhyndman** [comment]
@ekote . This is not the place for a general discussion. Ask on crossvalidated.com.
