### ISSUE TITLE
Problems with time stamps on forecast objects

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#753]
See https://stackoverflow.com/q/53055558/144157

**Comment by mitchelloharawild** [comment]
I believe this is a bug with the datasets package.

The `AirPassengers` time series is invalid as the `tsp` is incorrect (handling of floating point math near the end tsp value must have changed since the object's creation).

Somewhere in `auto.arima`, `stlf`, and `tbats`, a call to `ts` is made which fixes the `tsp` for this object, and these fixes do not occur in `ets` and `nnetar`. For example, `auto.arima` calls `subset`, which recreates the `ts` even if no subsets are made.

``` r
library(forecast)
y <- ts(AirPassengers, start = start(AirPassengers), frequency = frequency(AirPassengers))

# Something about the objects are different!
identical(AirPassengers, y)
#> [1] FALSE
# tsp is different
identical(tsp(AirPassengers), tsp(y))
#> [1] FALSE
# With tolerance, the objects are identical
all.equal(AirPassengers, y)
#> [1] TRUE

# Combining forecasts now works!
h <- 1
ETS <- forecast(ets(y), h = h)
ARIMA <- forecast(auto.arima(y, lambda = 0, biasadj = TRUE), h = h)
STL <- stlf(y, lambda = 0, h = h, biasadj = TRUE)
NNAR <- forecast(nnetar(y), h = h)
TBATS <- forecast(tbats(y, biasadj = TRUE), h = h)
Combination <- (ETS[["mean"]] + ARIMA[["mean"]] + STL[["mean"]] + 
                  NNAR[["mean"]] + TBATS[["mean"]]) / 5
```

Created on 2018-10-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mitchelloharawild** [comment]
Example 2 should be fixed in https://github.com/robjhyndman/forecast/commit/968a4fa4ec08c36b12d4981fd23679a51cb4823f, but it again relates to rounding of `tsp` elements.
