### ISSUE TITLE
auto.arima infinite loop

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#764]
```r
xd <- ts(c(23786, 25955, 54373, 21561, 14552, 13284, 12714, 11821, 15445, 21307, 17228, 
  20007, 23065, 32811, 43147, 15127, 13497, 12224, 11412, 11888, 14210,18978, 15782, 
  17216, 16417, 22861, 42616, 17057,  9741, 10503,  7170, 10686,  9762, 15773, 15280, 
  13212, 14784, 26104, 29947), 
  frequency = 12)
auto.arima(xd, trace=TRUE, approximation=FALSE, allowmean=FALSE, allowdrift = FALSE, 
  max.p=1, max.q=0, max.P=1, max.Q=0, xreg=seq_along(xd))
```

**Comment by mitchelloharawild** [comment]
How do you want this to be resolved?
The issue comes from the recursion for checking stationarity of regression residuals (line 690 newarima2.R).

- When `auto.arima` is ran with `d=1`, `ndiffs(res) == 0`
- When `auto.arima` is ran with `d=0`, `ndiffs(res) == 1`

As `ndiffs(res) != d`, the recursion will always occur in this case.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/a53223db98b56c0640110de2c2f718d107154875
