### ISSUE TITLE
autolayer not working with forecast objects in latest version of colorspace package

### ISSUE THREAD

**Issue by shane-kercheval** [robjhyndman/forecast#766]
I updated all my R packages to the latest versions

now, if i do 

```
a10 %>%
    autoplot() +
    autolayer(ets(a10) %>% forecast(h=24))
```

I get `Error: 'coerce' is not an exported object from 'namespace:colorspace'`

and from looking at https://cran.r-project.org/web/packages/colorspace/index.html

I can see that it had a recent update `2019-01-13`, so i'm guessing something changed in that package that is affecting the `forecast` package.

**Comment by shane-kercheval** [comment]
if I reinstall the previous version of `colorspace` via

```
packageurl <- "https://cran.r-project.org/src/contrib/Archive/colorspace/colorspace_1.3-2.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

I can confirm that the code now executes successfully

**Comment by mitchelloharawild** [comment]
Please install the latest version from GitHub and try again.
This was fixed in
https://github.com/robjhyndman/forecast/commit/7457fed9d9a36e313bca0e5a581586d07ab2e23e

**Comment by shane-kercheval** [comment]
I have version `8.4` installed, which seems like the latest cran version.

I get some errors when I try to install via `devtools::install_github("robjhyndman/forecast")`: `library not found for -lgfortran` then `install.packages('lgfortran') -> Warning in install.packages : package ‘lgfortran’ is not available (for R version 3.5.2)`

But regardless, I don't think the majority of users of the `forecast` package will be installing from source, so not sure this is a great option.

**Comment by mitchelloharawild** [comment]
This issue was introduced two days ago when the colorspace package was
updated in CRAN. This colorspace update has changed their exports and
consequently broken our package. In theory, CRAN (and the colorspace
package) is supposed to check that their changes do not break any packages
that depend on it (including forecast). For some unknown reason this did
not occur, and we were not notified and not given time to fix this issue.

Regardless of why, we have been preparing a CRAN release for 2 months and
are waiting on one dependent package to update so that we can release. We
are doing everything we can to release this update as soon as possible.

Your options until the next version is on cran is to either:
1. Install the previous version of colorspace (as you have done)
2. Install the development version of forecast

**Comment by shane-kercheval** [comment]
makes sense, thanks for the information!

That was my next question, if you're planning on releasing to CRAN in the near future i'll stick with option 1, and just update according.

Thanks again!

**Comment by mitchelloharawild** [comment]
forecast 8.5 is now on cran.
