### ISSUE TITLE
arimax warning. Why?

### ISSUE THREAD

**Issue by espher1987** [robjhyndman/forecast#771]
Hi, i am getting problems with the last updated on cran. My goal is to get an Arimax model, so this is a basic example of the warning i get.

in the past. in forecast 8.4 using the next example.

```
library(forecast)
set.seed(1)
x <- rbinom(length(AirPassengers),1,0.5)
model <- Arima(AirPassengers,order = c(1,1,0),c(1,1,0),xreg = x)
forecast(model,xreg=c(1,1,1,0,0))
```
i dont get any error everything looks great, not warning either.

but in forecast 8.5
the same code give me this:

> Warning message:
> In forecast.Arima(model, xreg = c(1, 1, 1, 0, 0)) :
>   xreg contains different column names from the xreg used in training. Please check that the regressors are in the same order.
>

i must say i am getting the forecast information. But why this warning? based in 8.5 documentation xreg can be "A numerical vector".

same happens even if i do:

```
library(forecast)
set.seed(1)
x <- rbinom(length(AirPassengers),1,0.5)
model <- Arima(AirPassengers,order = c(1,1,0),c(1,1,0),xreg = x)

x <- c(1,1,1,0,0)
forecast(model,xreg=x)
```

Thanks in advance.

**Comment by mitchelloharawild** [comment]
Hi,

This issue is a warning and there should be no subsequent issues with the
output you are receiving. In the latest update we made some changes to
exogenous regressors for ARIMA models to make it less likely for user
error. One common issue was the naming of regressors in the model. As part
of this, exogenous regressors now should be a named matrix of regressors.
The names of the matrix provided to the forecast function should match the
one used to train the model (so that correct columns are used for the
appropriate xreg terms).

**Comment by hupseb** [comment]
Sorry, but this change is confusing.
