### ISSUE TITLE
ets() breaks with this particular time series

### ISSUE THREAD

**Issue by lccambiaghi** [robjhyndman/forecast#827]
```
library(forecast)

data <- c(101, 45, 39, 16, 17, 32, 26, 32, 60, 29, 75, 28, 28, 63, 60, 51, 69, 71, 46, 71, 44, 41, 18, 81, 82, 59, 65, 42, 73, 71,117, 78,102, 99, 77, 53, 65,113, 56, 53, 51, 60, 20,109,126,228,  8, 80, 37,161, 85, 68,110,101, 99, 78,146,145, 23, 74, 87, 93,136, 56, 87,112, 96, 61, 72, 68,145,118,105,106, 73, 40, 92,110, 54, 58, 74,103,102, 43, 68, 58, 48, 29, 61, 69, 81, 79, 39, 56, 78, 90, 58, 45, 20, 31, 13, 54, 19,  6, 13, 29, 40, 38, 26, 65, 28, 39, 42, 49, 49, 45, 53, 46, 41,139, 96, 83,105, 68, 99,105, 95,102, 33,136, 78, 62,161,132,166,152, 78, 87, 64, 77,134,121,185,158,129,133,158,146,126,127,124,126, 91, 63, 81, 17, 24, 43, 42, 52, 53, 48, 64, 22,103,150, 42,118, 66, 58, 38,182, 94,153, 40,201, 90,146,118, 70, 32, 50,206,180,112, 88,127,171,101,105,103,163, 91,117, 56, 77, 75, 84, 98, 68,118, 84, 70, 47, 76, 48, 23, 74, 32, 45, 35, 23,  0, 10,  3, 10, 11,  0, 11, 24, 24, 30, 48, 21, 52, 21, 43, 64, 68, 41, 65, 71, 36, 30, 42, 57, 78, 60, 50, 27, 32, 90, 56, 55,100, 63, 44, 48, 39, 44)

data_model_structure <- data[1:197]
model <- data_model_structure %>% ts() %>% ets()

data_train <- data[1:213]
refit <- ets(data_train, model)
```

I think the problem is in the BoxCox transformation.

If I set `lambda='auto'` the model still breaks. 

If I set `lambda=1` it does not break.

**Comment by robjhyndman** [comment]
The problem is that the first 197 observations do not include a zero, and the model chosen is multiplicative. When you add the next few observations a zero is included, and the multiplicative model is no longer appropriate.

The Box Cox transformation is just masking the problem. Setting `lambda = 'auto'` will set a value of lambda which will cause problems with zeros as well. Setting `lambda=1` gives essentially no transformation, so no problems in transforming zeros. But setting lambda equal to anything forces `ets()` to only consider additive models.

The best solution would be to  avoid multiplicative models from the start:

```r
model <- data_model_structure %>% ts() %>% ets(additive=TRUE)
```
