### ISSUE TITLE
accuracy - ERROR: number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by marcosaramburu** [robjhyndman/forecast#88]
Hi Rob,

I'm getting an error when I try to run the "accuracy" function for a weekly forecast.

I followed your suggestions (on http://robjhyndman.com/hyndsight/forecasting-weekly-data/) and set the frequency of the "ts" object as = Year + Day_Of_Year / 7 / 365.25. This is an In-Sample ts with 156 periods. I then run the Regression with ARIMA errors as it is shown trying to forecast 38 periods (Out-Of-Sample).

At last, I tried to run the accuracy procedure with the Forecast against the Out-Of-Sample and I received the error message "Error in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]),  : number of items to replace is not a multiple of replacement length"

I tried to debug the code and founded that the errors shows up when trying to calculate the MASE metric (error.R - Line 64 - Code: "nsd <- diff(dx, lag = tspdx[3L], differences = D"). I also tried to supply the d and D parameters but the functions seems to ignore those values and find them anyway.

Is this a bug or I am messing it up somewhere?

Thanks for your help!

PS: thanks also for your awesome work here!

**Comment by saulfeliz** [comment]
I had the same issue. I think the root cause might be coming from AUTO ARIMA?
Does this function call that other function? 

Here is the reproduced error:

library(forecast)
gas <- ts(read.csv("http://robjhyndman.com/data/gasoline.csv", header=FALSE)[,1], 
          freq=365.25/7, start=1991+31/365.25)
auto.arima(gas)

RESULT:
Error in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]),  : 
  number of items to replace is not a multiple of replacement length

However, if you read in the CSV without the additional arguments, it works:

gas2<- ts(read.csv("http://robjhyndman.com/data/gasoline.csv", header=FALSE))

auto.arima(gas2)

RESULT:
Series: gas2 
ARIMA(0,1,1)                    

Coefficients:
          ma1
      -0.7373
s.e.   0.0245

sigma^2 estimated as 96471:  log likelihood=-5325.53
AIC=10655.05   AICc=10655.07   BIC=10664.28

**Comment by robjhyndman** [comment]
I cannot reproduce this error in the latest (github) version of the package.

**Comment by saulfeliz** [comment]
Is this different than the package available in CRAN? Two other colleagues got the same errors, running in different machines. We're all using forecast_6.1

**Comment by robjhyndman** [comment]
The github version is the current development version. Every few months I will copy it across to CRAN.

**Comment by saulfeliz** [comment]
got it. thanks!

**Comment by marcosaramburu** [comment]
Thanks for clarifying!
